[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  headers = { Access-Control-Allow-Origin = "*" }
[functions]
  included_files = ["controllers/**"]
[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "http://localhost:5173"
  Access-Control-Allow-Credentials = "true"